# Generated by Django 3.2.9 on 2021-12-26 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('fecha', models.TextField(verbose_name='Fecha')),
                ('tipo', models.TextField(verbose_name='Tipo')),
                ('dimensiones', models.TextField(verbose_name='Dimensiones')),
                ('lugar', models.TextField(verbose_name='Lugar')),
                ('artista', models.TextField(verbose_name='Artista')),
                ('expuesto', models.TextField(verbose_name='Expuesto')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('imagenTarjeta', models.ImageField(upload_to='', verbose_name='Imagen Tarjeta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tecnica', models.TextField(verbose_name='Técnica')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.museo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.obra')),
            ],
        ),
    ]
